### PR TITLE
Add "piston" keyword to Cargo.toml

### PR DESCRIPTION
**Pull request by bvssvni**
See https://github.com/PistonDevelopers/piston/issues/808
- Updated to gfx_texture 0.2.0
- Use minimum version in dependencies

### CODE REVIEW

**Comment by bvssvni** [comment]
@stjahns Could you add me as owner on crates.io?

**Comment by bvssvni** [comment]
@stjahns Ping!

**Comment by kvark** [comment]
Looks good!
@bvssvni: I believe @stjahns has been experiencing some login issues with GH. I'll ping him to get here soon, hold on.

**Comment by stjahns** [comment]
Hey! Apparently changing your phone number causes problems for 2 factor auth, sorry for the huge delay. I'll add you as owner when I get home tonight!

**Comment by bvssvni** [comment]
@stjahns Oh, I hope it's working for you now!

**Comment by stjahns** [comment]
Done! Sorry I'm not really able to contribute anymore :( give me a shout if there's anything else I can do to pass off ownership!

**Pull request merged**
