### PR TITLE
It compiles!

### PR DESCRIPTION
**Pull request by bvssvni**
- Bumped to 0.9.0

### CODE REVIEW

**Comment by kvark** [comment]
Wow, impressive work @bvssvni !

**Comment by bvssvni** [comment]
I get an error when trying to update [skeleton_animation_demo](https://github.com/pistondevelopers/skeletal_animation_demo):

```
$ RUST_BACKTRACE=1 cargo run --release
    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/demo`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DescriptorInit(VertexImport(0, None))', ../src/libcore/result.rs:788
stack backtrace:
   1:        0x10c6ae28a - std::sys::backtrace::tracing::imp::write::h482d45d91246faa2
   2:        0x10c6b0bf0 - std::panicking::default_hook::_{{closure}}::h89158f66286b674e
   3:        0x10c6afe20 - std::panicking::default_hook::h9e30d428ee3b0c43
   4:        0x10c6b04a6 - std::panicking::rust_panic_with_hook::h2224f33fb7bf2f4c
   5:        0x10c6b0344 - std::panicking::begin_panic::hcb11a4dc6d779ae5
   6:        0x10c6b0252 - std::panicking::begin_panic_fmt::h310416c62f3935b3
   7:        0x10c6b01b7 - rust_begin_unwind
   8:        0x10c6dcb50 - core::panicking::panic_fmt::hc5789f4e80194729
   9:        0x10c51ccf2 - core::result::unwrap_failed::h7c9acc20c5c0b316
  10:        0x10c55a186 - _<demo..demo..Demo<R, TAnim, TSkinning>>::new::h555bbfe4ee86eefe
  11:        0x10c55eb24 - demo::main::h9cd0945ee520db16
  12:        0x10c6b11da - __rust_maybe_catch_panic
  13:        0x10c6af8ee - std::rt::lang_start::h352a66f5026f54bd
error: Process didn't exit successfully: `target/release/demo` (exit code: 101)
Svens-MacBook-Air:skeletal_animation_demo sven$ 
```

**Comment by kvark** [comment]
It's reported if the vertex attribute 0 wasn't found in the PSO definition. If you do a cargo override to the latest `gfx`, it will report the name.
Looking through this code, I don't see why they would be mismatched though, assuming proper shaders are used with proper PSOs.

**Comment by bvssvni** [comment]
I think I'm closing in:

```
u_skinning_transforms: &[],
```

This was set to an empty slice because I did not know what to put there. It expects `&[(&str, gfx::pso::buffer::Element<gfx::format::Format>, u8)]`.

**Comment by bvssvni** [comment]
@kvark Thanks for you comment https://github.com/gfx-rs/gfx/issues/1038#issuecomment-245288631. I think I'm in a bit need of mentoring here. So far I have 400 lines of notes just for this upgrade, but now I'm lost. Now that I'm so close, could you help me through the last step?

Also, some things that might be useful for the docs: I think I have a clear picture when to use `gfx_pipeline!` or `gfx_pipeline_base!` which could be easily added with some comments. What is lacking in the docs is a table that tells you how to map from shader code to Gfx types.

**Comment by kvark** [comment]
@bvssvni I'll take a good look at this problem tonight.

> What is lacking in the docs is a table that tells you how to map from shader code to Gfx types.

Good point! I guess we can put it in the corresponding GL backend documentation/readme (cc @BastaCyclop).

**Comment by bvssvni** [comment]
I've opened https://github.com/PistonDevelopers/skeletal_animation_demo/pull/25. If you override skeletal_animation in ".cargo/config" it should be compile. It crashes when running because of the stuff above.

**Comment by kvark** [comment]
@bvssvni do you mind waiting a bit for this one? 
See, the current approach of `skeletal_animation` is wonky. It tries to use different shaders with the same inputs, _except_ for the constant buffer, it tries to hack the API, and we didn't cater to that. One could have 2 different PSOs there, but it would involve quite a bit of code changes here.
The proper solution would be for `gfx` to provide `RawConstantBuffer` component (similar to `RawVertexBuffer`) for run-time trade-offs like we need here. I've already implemented it for our master branch (PR incoming) but testing it is problematic because we have several other API changes (since v0.12), so I'd have to override and fix all the libraries between GFX and skeletal_animation.
I'll make a second attempt to back-port it to v0.12 and release a minor patch now.

**Comment by kvark** [comment]
Superseded by #49

**Comment by kvark** [comment]
@bvssvni P.S. Indeed this required my intervention. Sorry for not recognizing this earlier!

**Pull request closed without merging**
